name: Pytest

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Testing Date Titles Folders
        run: |
          python3 -m unittest resources/get_dates_titles_test.py
      - name: Testing Event List
        run: |
          python3 -m unittest resources/get_event_list_test.py
      - name: Testing Add Event
        run: |
          python3 -m unittest to_add_events_test.py
      - name: Testing Delete Event
        run: |
          python3 -m unittest to_delete_events_test.py
